version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./services/nginx
    ports:
      - '80:80'
    links:
      - service1
      - service2
  service1:
    build:
      context: ./services/service1
    expose:
      - 3000
  service2:
    build:
      context: ./services/service2
    expose:
      - 3000